
```{r}
library(BART)
options("install.lock"=FALSE)
install.packages("tidyverse")

```


```{r}
# read in the dataset
setwd("../pymc_bart")
data = read.csv("./vet_lung_canc.csv") 


# Convert to a matrix
data["Status"] = ifelse(data["Status"] == "True", 1, 0)
data = as.matrix(data)
```

# preprocessing
```{r}
# set vars
delta = data[,"Status"]
time = data[,"Survival_in_days"]
data_x = data[,c("Age_in_years", "Celltype.large", "Celltype.smallcell", "Celltype.squamous", "Karnofsky_score", "Months_from_Diagnosis", "Prior_therapy.yes", "Treatment.test")]


# check vars
delta
time
data_x[1,]

# get the pre
pre = surv.pre.bart(time, delta, data_x, data_x)

# check pre
str(pre)



# For train expand on the set of times given in time set up to the end time (do not fill gaps)
# head(pre$tx.train[,c("t", "Age_in_years")], 501)
# data_x[,c("Age_in_years")]
# time
# delta
# head(pre$y.train, n=101)

# For test we test on all time points in time set
# head(pre$tx.test[,c("t", "Age_in_years")], 102)

# check times are the same 
# length(sort(unique(time)))
# setdiff(sort(unique(time)), pre$times)
# setdiff( pre$times,sort(unique(time)))
```

```{r}
# train model
post = mc.surv.bart(x.train=data_x, times = time, delta=delta, mc.cores=8, seed=99)

str(post)
str(data_x)
str(pre$tx.train)
str(pre$tx.test)

# get predictions on dataset
pred = predict(post, newdata=pre$tx.test, mc.cores=8)
str(pred)

# set number of patients var
N = dim(data_x)[1]
surv_mean = apply(t(matrix(pred$surv.test.mean, pred$K, N)), 2, mean) 
str(pred)

apply(t(matrix(apply(pred$yhat.test, 2, mean), pred$K, N)),2,mean)

surv_out = data.frame("times" = pred$times, "surv" = surv_mean)
surv_out
write.csv(surv_out, "rbart_lung_mean.csv")
```

```{r}
str(pred)

probs_xx = apply(pred$prob.test, 2, mean)

prob_xx2 = t(matrix(probs_xx, nrow=pred$K, ncol=N))

str(prob_xx2)
prob_xx3 = 1-prob_xx2
str(prob_xx3)

surv_xx = t(apply(prob_xx3, 1, cumprod))

str(surv_xx)
surv_xx2 = apply(surv_xx, 2, mean)

surv_xx2
surv_mean

###
str(pred$prob.test)
probs_x2 = 1-pred$prob.test
probs_x2[1,]


H = nrow(pred$tx.test)/pred$K

K = pred$K
surv_x2 = probs_x2
for(h in 1:H){
    for(j in 2:K){
        l = K*(h-1)+j
        surv_x2[,l] = surv_x2[,l-1]*surv_x2[,l]
    }
}
surv_x2_mean
surv_x2_mean = apply(surv_x2, 2, mean)

pat_surv_x2 = t(matrix(surv_x2_mean, nrow=K, ncol=N))

pat_surv_x2[1,]

str(surv_x2_mean)

test_surv = apply(t(matrix(surv_x2_mean, nrow=K, ncol=N)), 2, mean)


str(pred$surv.test.mean)
tru_surv = apply(t(matrix(pred$surv.test.mean, nrow=K, ncol=N)), 2, mean)

test_surv
tru_surv
```

```{r}
# check single patient
str(pred)
b_offset = pred$binaryOffset
offset =post$offset
offset
post$offset
str(post)

pred$yhat.test[1, 1:101]


pat1 = apply(pred$prob.test,2,mean)[1:101]

apply(pred$yhat.test, 2, mean)[1:101]

install.packages("pryr")
library("pryr")
mem_used()
pred = c()

```